import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import NavLinks from "./components/navlinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav>
          <NavLinks />
        </Nav>
        {children}
      </body>
    </html>
  );
}
